fix ubuntu setup bugs

diff --git a/scripts/components/ubuntu_setup b/scripts/components/ubuntu_setup
--- a/scripts/components/ubuntu_setup
+++ b/scripts/components/ubuntu_setup
@@ -8,31 +8,38 @@ UbuntuSetup(){
     sudopass=$(InputSudoPass)
     echo $sudopass | sudo -S -v
     # パッケージ自動更新ツールインストール
-    if ! command -v unattended-upgrade &> /dev/null; then
+    if ! command -v unattended-upgrades &> /dev/null; then
         echo
-        echo -e "${YELLOW}セキュリティアップデート自動適用ツール(unattended-upgrade)をインストールします${NC}\n"
+        echo -e "${YELLOW}セキュリティアップデート自動適用ツール(unattended-upgrades)をインストールします${NC}\n"
         sudo apt install unattended-upgrades -y > /dev/null 2>&1
         sudo DEBIAN_FRONTEND=noninteractive dpkg-reconfigure -f noninteractive unattended-upgrades
-        echo -e "${YELLOW}unattended-upgradeをインストールしました${NC}\n"
+        echo -e "${YELLOW}unattended-upgradesをインストールしました${NC}\n"
         sleep 1
     else
-        #ON/OFF設定確認
-        is_enabled=$(sudo dpkg-reconfigure -f noninteractive unattended-upgrades | grep -c 'enabled')
-        if [ $is_enabled -eq 0 ]; then
-            echo
-            echo -e "${YELLOW}unattended-upgradeが無効になっています。有効化します${NC}\n"
-            sudo DEBIAN_FRONTEND=noninteractive dpkg-reconfigure -f noninteractive unattended-upgrades
-            echo -e "${YELLOW}unattended-upgradeを有効化しました${NC}\n"
-            sleep 1
+        # ON/OFF設定確認
+        auto_conf="/etc/apt/apt.conf.d/20auto-upgrades"
+        if [ -f "$auto_conf" ]; then
+            is_enabled=$(grep -c 'Unattended-Upgrade "1"' "$auto_conf")
         else
-            echo -e "${GREEN}unattended-upgradeは既に有効化されています${NC}\n"
-            sleep 1
+            is_enabled=0
         fi
-        echo -e "${GREEN}unattended-upgradeは既にインストールされています${NC}\n"
+
+        if [ "$is_enabled" -eq 0 ]; then
+            echo
+            echo -e "${YELLOW}unattended-upgradesが無効になっています。有効化します${NC}\n"
+            sudo bash -c 'cat > /etc/apt/apt.conf.d/20auto-upgrades <<EOF
+    APT::Periodic::Update-Package-Lists "1";
+    APT::Periodic::Unattended-Upgrade "1";
+    EOF'
+            echo -e "${GREEN}unattended-upgradesを有効化しました${NC}\n"
+        else
+            echo -e "${GREEN}unattended-upgradesは既に有効化されています${NC}\n"
+        fi
+        echo -e "${GREEN}unattended-upgradesは既にインストールされています${NC}\n"
         sleep 1
     fi
-
     read -p "Enterを押すと続行します..." 
+    echo
 
     #ブラケットペーストモードOFF
     echo -e "${YELLOW}ブラケットペーストモードを無効化します${NC}\n"
@@ -49,6 +56,8 @@ UbuntuSetup(){
     else
         echo "✅ ブラケットペーストモードは既に無効化されています。"
     fi
+    echo
+
 
     #デーモン自動再起動回避
     echo -e "${YELLOW}デーモン自動再起動回避設定を確認します${NC}\n"
@@ -64,6 +73,7 @@ UbuntuSetup(){
     fi
     sleep 1
     read -p "Enterを押すと続行します..."
+    echo
 
     #共有メモリ設定強化
     if ! grep -qE '^[^#]*tmpfs[[:space:]]+/dev/shm' /etc/fstab; then
@@ -78,11 +88,11 @@ UbuntuSetup(){
         sleep 1
     fi
     read -p "Enterを押すと続行します..."
+    echo
 
     # ed25519 SSH鍵作成
     if [ ! -f "${HOME}/.ssh/authorized_keys" ]; then
         #SSH鍵ファイル作成選択
-        echo
         Gum_Confirm_YesNo "ed25519 SSH鍵を作成しますか?" "Yes" "No"
         if [ $iniSettings = "Yes" ]; then
             sleep 1
@@ -93,7 +103,7 @@ UbuntuSetup(){
             echo -e "${YELLOW}公開鍵をauthorized_keysに追加しました${NC}\n"
             chmod 700 ~/.ssh
             echo -e "鍵ペアを作成しました。${YELLOW}~/.ssh/ssh_ed25519(秘密鍵)${NC}と${YELLOW}~/.ssh/ssh_ed25519.pub(公開鍵)${NC}に保存されています"
-            echo -e "${RED}2つのファイルを安全な場所にバックアップしてください${NC}\n"
+            echo -e "${RED}2つのファイルをダウンロードし安全な場所にバックアップしてください${NC}\n"
             echo -e "次回SSH接続の際は、ターミナルソフトに${YELLOW}ssh_ed25519${NC}を設定して接続してください。\n"
             sleep 2
         else
@@ -335,3 +345,30 @@ EOF
     read -p "Enterを押すとセッションを終了します..."
     tmux kill-session -t spokit
 }
+
+
+#Ubuntuセキュリティ設定開始確認
+#設定内容列挙
+echo -e "${YELLOW}このモードでは以下のUbuntu初期設定を行います${NC}\n"
+echo -e "1.セキュリティアップデート自動適用ツール(unattended-upgrade)インストールと有効化"
+echo -e "2.ブラケットペーストモード無効化"
+echo -e "3.デーモン自動再起動回避設定"
+echo -e "4./dev/shmにtmpfsを設定"
+echo -e "5.ed25519 SSH鍵作成"
+echo -e "6.chronyインストールとSPOKIT推奨設定適用"
+echo -e "7.ssh設定変更(選択制)"
+echo -e "  ・KbdInteractiveAuthentication無効化"
+echo -e "  ・PasswordAuthentication無効化"
+echo -e "  ・PermitRootLogin無効化"
+echo -e "  ・PermitEmptyPasswords無効化"
+echo -e "  ・ssh Port番号変更"
+echo -e "8.fail2banインストールと設定"
+echo -e "9.ufw有効化とsshポート許可設定\n"
+sleep 2
+Gum_Confirm_YesNo "Ubuntu初期設定を開始しますか?" "Yes" "No"
+if [ $iniSettings = "Yes" ]; then
+    UbuntuSetup
+else
+    echo -e "${YELLOW}Ubuntu初期設定をスキップしました${NC}\n"
+    sleep 1
+fi
